import type { Company, Pitch } from '../types';

export const mockCompany: Company = {
  id: '1',
  slug: 'acme-corp',
  name: 'ACME株式会社',
  description: 'テクノロジーで日本のビジネスをより良くする会社です。',
  industry: 'IT・テクノロジー',
  website: 'https://acme.example.com',
  receivingConditions: [
    '導入実績が3社以上あるサービス',
    '初期費用と月額費用が資料に明記されていること',
    '無料トライアルまたはデモが可能なもの',
    '中小企業向けの料金プランがあること',
  ],
  departments: [
    { id: 'd1', companyId: '1', name: 'マーケティング部', category: 'marketing', contactEmail: 'marketing@acme.example.com', allowPitches: true },
    { id: 'd2', companyId: '1', name: 'システム部', category: 'system', contactEmail: 'system@acme.example.com', allowPitches: true },
    { id: 'd3', companyId: '1', name: '人事部', category: 'hr', contactEmail: 'hr@acme.example.com', allowPitches: true },
    { id: 'd4', companyId: '1', name: '経営企画室', category: 'executive', allowPitches: false },
  ],
  createdAt: '2024-01-01T00:00:00Z',
};

export const mockPitches: Pitch[] = [
  {
    id: 'p1',
    refNumber: 'PL-2024-0001',
    sender: { id: 'u1', name: '田中 太郎', companyName: 'テックソリューションズ株式会社', email: 'tanaka@tech.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=1' },
    companyId: '1',
    departmentId: 'd1',
    title: '広告運用の自動化ツールのご提案',
    body: 'はじめまして。テックソリューションズの田中です。\n\n弊社の広告運用自動化ツール「AdPilot」についてご提案させてください。AIを活用した入札最適化により、広告費を平均30%削減しながらCVRを向上させることができます。\n\n添付資料にて詳細をご確認いただけます。ご興味があればぜひお声がけください。',
    attachments: [
      { id: 'a1', name: 'AdPilot_サービス資料.pdf', type: 'pdf', url: '#', size: 2400000 },
    ],
    category: 'marketing',
    status: 'unread',
    createdAt: '2024-11-20T10:30:00Z',
    original: {
      headline: '貴社のマーケティング体制に合わせた運用プランをご用意しました',
      points: [
        '現在ご利用中の広告媒体に追加導入できる構成',
        '繁忙期を避けた段階的な導入スケジュール案つき',
        'マーケティング部の運用工数を想定した初期設定の代行',
      ],
    },
    reading: {
      materialName: 'AdPilot_サービス資料.pdf',
      pages: [
        { page: 1, seconds: 8 },
        { page: 2, seconds: 14 },
        { page: 3, seconds: 47 },
        { page: 4, seconds: 12 },
        { page: 5, seconds: 92 },
        { page: 6, seconds: 22 },
        { page: 7, seconds: 6 },
      ],
    },
  },
  {
    id: 'p2',
    refNumber: 'PL-2024-0002',
    sender: { id: 'u2', name: '鈴木 花子', companyName: 'クラウドベース株式会社', email: 'suzuki@cloudbase.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=5' },
    companyId: '1',
    departmentId: 'd2',
    title: 'セキュリティ診断サービスのご案内',
    body: 'お世話になります。クラウドベースの鈴木です。\n\n昨今のサイバー攻撃増加を受け、弊社のセキュリティ診断サービスをご案内します。Webアプリケーションの脆弱性診断から、ネットワーク全体のリスク評価まで対応しております。\n\n初回診断は無料でご提供可能です。',
    attachments: [
      { id: 'a2', name: 'セキュリティ診断_概要.pdf', type: 'pdf', url: '#', size: 1200000 },
      { id: 'a3', name: '導入事例紹介', type: 'link', url: 'https://example.com' },
    ],
    category: 'system',
    status: 'read',
    createdAt: '2024-11-19T14:00:00Z',
  },
  {
    id: 'p3',
    refNumber: 'PL-2024-0003',
    sender: { id: 'u3', name: '伊藤 健一', companyName: 'HRテック合同会社', email: 'ito@hrtech.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=8' },
    companyId: '1',
    departmentId: 'd3',
    title: '採用管理システム「HireFlow」のご提案',
    body: '採用担当者様\n\nHRテックの伊藤です。採用工数を60%削減した実績のある採用管理システム「HireFlow」をご紹介します。\n\nAIによる書類選考、面接日程の自動調整、候補者へのコミュニケーション一元管理など、採用全体をサポートします。',
    attachments: [
      { id: 'a4', name: 'HireFlow_製品動画', type: 'video', url: '#' },
    ],
    category: 'hr',
    status: 'saved',
    createdAt: '2024-11-18T09:15:00Z',
  },
  {
    id: 'p4',
    refNumber: 'PL-2024-0004',
    sender: { id: 'u4', name: '山本 三郎', companyName: 'オフィスサプライ株式会社', email: 'yamamoto@office.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=12' },
    companyId: '1', departmentId: 'd4',
    title: 'オフィス備品の定期配送サービス',
    body: '消耗品の発注業務を自動化するサービスのご案内です。',
    attachments: [{ id: 'a5', name: 'サービス概要.pdf', type: 'pdf', url: '#', size: 900000 }],
    category: 'other', status: 'read', createdAt: '2024-08-10T09:00:00Z',
  },
  {
    id: 'p5',
    refNumber: 'PL-2024-0005',
    sender: { id: 'u5', name: '中村 四郎', companyName: 'リーガルテック株式会社', email: 'nakamura@legal.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=15' },
    companyId: '1', departmentId: 'd4',
    title: '契約書管理システムのご提案',
    body: '契約書の電子化と期限管理を一元化するシステムです。',
    attachments: [{ id: 'a6', name: '製品資料.pdf', type: 'pdf', url: '#', size: 1500000 }],
    category: 'executive', status: 'read', createdAt: '2024-06-22T11:00:00Z',
  },
  {
    id: 'p6',
    refNumber: 'PL-2024-0006',
    sender: { id: 'u6', name: '小林 五郎', companyName: 'グロースマーケ株式会社', email: 'kobayashi@growth.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=20' },
    companyId: '1', departmentId: 'd1',
    title: 'SNS運用代行のご案内',
    body: 'SNSアカウントの運用を月額制で代行いたします。',
    attachments: [{ id: 'a7', name: '実績資料.pdf', type: 'pdf', url: '#', size: 1100000 }],
    category: 'marketing', status: 'read', createdAt: '2024-03-15T13:30:00Z',
  },
  {
    id: 'p7',
    refNumber: 'PL-2024-0007',
    sender: { id: 'u7', name: '加藤 六子', companyName: 'クラウド会計株式会社', email: 'kato@account.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=25' },
    companyId: '1', departmentId: 'd4',
    title: 'クラウド会計ソフトの乗り換え提案',
    body: '会計業務を効率化するクラウドソフトへの乗り換えをご提案します。',
    attachments: [{ id: 'a8', name: '比較資料.pdf', type: 'pdf', url: '#', size: 1300000 }],
    category: 'finance', status: 'read', createdAt: '2023-12-05T10:00:00Z',
  },
  {
    id: 'p8',
    refNumber: 'PL-2024-0008',
    sender: { id: 'u8', name: '吉田 七海', companyName: 'タレントマネジメント株式会社', email: 'yoshida@talent.example.com', avatarUrl: 'https://i.pravatar.cc/40?img=30' },
    companyId: '1', departmentId: 'd3',
    title: '人材育成研修プログラムのご案内',
    body: '管理職向けの研修プログラムをご提案します。',
    attachments: [{ id: 'a9', name: '研修概要.pdf', type: 'pdf', url: '#', size: 800000 }],
    category: 'hr', status: 'read', createdAt: '2023-09-18T14:00:00Z',
  },
];


// ===== 運営者向け管理画面（AdminPage）用のデモ集計データ =====
// 実データはバックエンド接続後に差し替える前提のモック。
// 全プラットフォームに登録された受け手企業を表す。
export interface AdminCompany {
  id: string;
  name: string;
  slug: string;
  industry: string;
  plan: 'free' | 'paid';
  pitchCount: number;       // 受け取った提案総数
  savedCount: number;       // 保存した提案数
  dismissedCount: number;   // 却下した提案数
  daysSinceLastPitch: number; // 最終受信からの経過日数（アクティブ判定用）
  departmentCount: number;
  registeredMonth: string;  // 登録月 YYYY-MM
}

export const mockAdminCompanies: AdminCompany[] = [
  { id: '1', name: 'HanaIT合同会社', slug: 'hana-IT-1', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 14, savedCount: 2, dismissedCount: 3, daysSinceLastPitch: 5, departmentCount: 1, registeredMonth: '2024-11' },
  { id: '2', name: 'SoraIT有限会社', slug: 'sora-IT-2', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 1, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 2, departmentCount: 6, registeredMonth: '2024-09' },
  { id: '3', name: 'UminoIT法人', slug: 'umino-IT-3', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 47, savedCount: 9, dismissedCount: 13, daysSinceLastPitch: 2, departmentCount: 6, registeredMonth: '2025-01' },
  { id: '4', name: 'HikariIT株式会社', slug: 'hikari-IT-4', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 5, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 5, departmentCount: 3, registeredMonth: '2024-07' },
  { id: '5', name: 'SakuraIT合同会社', slug: 'sakura-IT-5', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 51, savedCount: 5, dismissedCount: 17, daysSinceLastPitch: 5, departmentCount: 5, registeredMonth: '2024-07' },
  { id: '6', name: 'MoriIT有限会社', slug: 'mori-IT-6', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 11, savedCount: 3, dismissedCount: 4, daysSinceLastPitch: 5, departmentCount: 3, registeredMonth: '2024-01' },
  { id: '7', name: 'YamatoIT法人', slug: 'yamato-IT-7', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 27, savedCount: 5, dismissedCount: 12, daysSinceLastPitch: 9, departmentCount: 2, registeredMonth: '2024-06' },
  { id: '8', name: 'NijiIT株式会社', slug: 'niji-IT-8', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 57, savedCount: 14, dismissedCount: 14, daysSinceLastPitch: 14, departmentCount: 4, registeredMonth: '2024-03' },
  { id: '9', name: 'MidoriIT合同会社', slug: 'midori-IT-9', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 11, savedCount: 1, dismissedCount: 3, daysSinceLastPitch: 2, departmentCount: 3, registeredMonth: '2024-04' },
  { id: '10', name: 'MizuIT有限会社', slug: 'mizu-IT-10', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 2, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 30, departmentCount: 4, registeredMonth: '2024-04' },
  { id: '11', name: 'KazeIT法人', slug: 'kaze-IT-11', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 54, savedCount: 8, dismissedCount: 14, daysSinceLastPitch: 90, departmentCount: 6, registeredMonth: '2024-09' },
  { id: '12', name: 'SakuraIT株式会社', slug: 'sakura-IT-12', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 10, savedCount: 1, dismissedCount: 4, daysSinceLastPitch: 90, departmentCount: 1, registeredMonth: '2024-08' },
  { id: '13', name: 'NijiIT合同会社', slug: 'niji-IT-13', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 22, savedCount: 4, dismissedCount: 4, daysSinceLastPitch: 45, departmentCount: 5, registeredMonth: '2024-10' },
  { id: '14', name: 'KazeIT有限会社', slug: 'kaze-IT-14', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 9, savedCount: 0, dismissedCount: 3, daysSinceLastPitch: 90, departmentCount: 6, registeredMonth: '2025-01' },
  { id: '15', name: 'UminoIT法人', slug: 'umino-IT-15', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 5, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 20, departmentCount: 5, registeredMonth: '2024-09' },
  { id: '16', name: 'UminoIT株式会社', slug: 'umino-IT-16', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 53, savedCount: 13, dismissedCount: 20, daysSinceLastPitch: 9, departmentCount: 5, registeredMonth: '2024-06' },
  { id: '17', name: 'HoshiIT合同会社', slug: 'hoshi-IT-17', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 46, savedCount: 10, dismissedCount: 10, daysSinceLastPitch: 30, departmentCount: 2, registeredMonth: '2025-02' },
  { id: '18', name: 'SakuraIT有限会社', slug: 'sakura-IT-18', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 5, registeredMonth: '2024-08' },
  { id: '19', name: 'SoraIT法人', slug: 'sora-IT-19', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 21, savedCount: 2, dismissedCount: 7, daysSinceLastPitch: 120, departmentCount: 5, registeredMonth: '2024-07' },
  { id: '20', name: 'TaniIT株式会社', slug: 'tani-IT-20', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 57, savedCount: 10, dismissedCount: 28, daysSinceLastPitch: 30, departmentCount: 4, registeredMonth: '2024-08' },
  { id: '21', name: 'AcmeIT合同会社', slug: 'acme-IT-21', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 4, savedCount: 0, dismissedCount: 1, daysSinceLastPitch: 120, departmentCount: 1, registeredMonth: '2024-04' },
  { id: '22', name: 'MoriIT有限会社', slug: 'mori-IT-22', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 16, savedCount: 5, dismissedCount: 7, daysSinceLastPitch: 5, departmentCount: 3, registeredMonth: '2024-09' },
  { id: '23', name: 'MoriIT法人', slug: 'mori-IT-23', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 26, savedCount: 7, dismissedCount: 12, daysSinceLastPitch: 120, departmentCount: 4, registeredMonth: '2024-08' },
  { id: '24', name: 'MidoriIT株式会社', slug: 'midori-IT-24', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 25, savedCount: 6, dismissedCount: 7, daysSinceLastPitch: 45, departmentCount: 6, registeredMonth: '2024-08' },
  { id: '25', name: 'SoraIT合同会社', slug: 'sora-IT-25', industry: 'IT・テクノロジー', plan: 'paid', pitchCount: 54, savedCount: 10, dismissedCount: 16, daysSinceLastPitch: 5, departmentCount: 2, registeredMonth: '2024-04' },
  { id: '26', name: 'HanaIT有限会社', slug: 'hana-IT-26', industry: 'IT・テクノロジー', plan: 'free', pitchCount: 3, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 5, departmentCount: 1, registeredMonth: '2024-08' },
  { id: '27', name: 'Mori製造法人', slug: 'mori-製造-27', industry: '製造業', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 2, registeredMonth: '2025-01' },
  { id: '28', name: 'Asahi製造株式会社', slug: 'asahi-製造-28', industry: '製造業', plan: 'free', pitchCount: 8, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 45, departmentCount: 3, registeredMonth: '2024-01' },
  { id: '29', name: 'Mizu製造合同会社', slug: 'mizu-製造-29', industry: '製造業', plan: 'paid', pitchCount: 42, savedCount: 11, dismissedCount: 17, daysSinceLastPitch: 90, departmentCount: 2, registeredMonth: '2024-11' },
  { id: '30', name: 'Midori製造有限会社', slug: 'midori-製造-30', industry: '製造業', plan: 'free', pitchCount: 4, savedCount: 0, dismissedCount: 1, daysSinceLastPitch: 30, departmentCount: 5, registeredMonth: '2024-01' },
  { id: '31', name: 'Ishi製造法人', slug: 'ishi-製造-31', industry: '製造業', plan: 'free', pitchCount: 9, savedCount: 3, dismissedCount: 2, daysSinceLastPitch: 9, departmentCount: 1, registeredMonth: '2024-02' },
  { id: '32', name: 'Midori製造株式会社', slug: 'midori-製造-32', industry: '製造業', plan: 'paid', pitchCount: 28, savedCount: 9, dismissedCount: 10, daysSinceLastPitch: 120, departmentCount: 5, registeredMonth: '2024-10' },
  { id: '33', name: 'Sora製造合同会社', slug: 'sora-製造-33', industry: '製造業', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 6, registeredMonth: '2024-05' },
  { id: '34', name: 'Sakura製造有限会社', slug: 'sakura-製造-34', industry: '製造業', plan: 'paid', pitchCount: 28, savedCount: 3, dismissedCount: 11, daysSinceLastPitch: 60, departmentCount: 1, registeredMonth: '2024-06' },
  { id: '35', name: 'Yamato製造法人', slug: 'yamato-製造-35', industry: '製造業', plan: 'free', pitchCount: 10, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 20, departmentCount: 1, registeredMonth: '2024-03' },
  { id: '36', name: 'Tani製造株式会社', slug: 'tani-製造-36', industry: '製造業', plan: 'paid', pitchCount: 36, savedCount: 7, dismissedCount: 13, daysSinceLastPitch: 20, departmentCount: 1, registeredMonth: '2024-10' },
  { id: '37', name: 'Hikari製造合同会社', slug: 'hikari-製造-37', industry: '製造業', plan: 'paid', pitchCount: 48, savedCount: 12, dismissedCount: 23, daysSinceLastPitch: 9, departmentCount: 1, registeredMonth: '2024-05' },
  { id: '38', name: 'Kaze製造有限会社', slug: 'kaze-製造-38', industry: '製造業', plan: 'paid', pitchCount: 22, savedCount: 5, dismissedCount: 9, daysSinceLastPitch: 14, departmentCount: 5, registeredMonth: '2024-11' },
  { id: '39', name: 'Tsubasa製造法人', slug: 'tsubasa-製造-39', industry: '製造業', plan: 'free', pitchCount: 1, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 2, departmentCount: 6, registeredMonth: '2024-06' },
  { id: '40', name: 'Tsubasa製造株式会社', slug: 'tsubasa-製造-40', industry: '製造業', plan: 'free', pitchCount: 23, savedCount: 4, dismissedCount: 4, daysSinceLastPitch: 5, departmentCount: 5, registeredMonth: '2024-12' },
  { id: '41', name: 'Hoshi製造合同会社', slug: 'hoshi-製造-41', industry: '製造業', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 3, registeredMonth: '2024-01' },
  { id: '42', name: 'Hana製造有限会社', slug: 'hana-製造-42', industry: '製造業', plan: 'free', pitchCount: 15, savedCount: 2, dismissedCount: 4, daysSinceLastPitch: 5, departmentCount: 4, registeredMonth: '2024-06' },
  { id: '43', name: 'Acme製造法人', slug: 'acme-製造-43', industry: '製造業', plan: 'paid', pitchCount: 60, savedCount: 19, dismissedCount: 27, daysSinceLastPitch: 9, departmentCount: 2, registeredMonth: '2024-07' },
  { id: '44', name: 'Umino製造株式会社', slug: 'umino-製造-44', industry: '製造業', plan: 'free', pitchCount: 34, savedCount: 9, dismissedCount: 14, daysSinceLastPitch: 14, departmentCount: 6, registeredMonth: '2024-05' },
  { id: '45', name: 'Niji製造合同会社', slug: 'niji-製造-45', industry: '製造業', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 3, registeredMonth: '2025-02' },
  { id: '46', name: 'Sakura製造有限会社', slug: 'sakura-製造-46', industry: '製造業', plan: 'free', pitchCount: 4, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 20, departmentCount: 3, registeredMonth: '2025-02' },
  { id: '47', name: 'Kaze製造法人', slug: 'kaze-製造-47', industry: '製造業', plan: 'free', pitchCount: 9, savedCount: 3, dismissedCount: 3, daysSinceLastPitch: 2, departmentCount: 2, registeredMonth: '2024-02' },
  { id: '48', name: 'Ishi製造株式会社', slug: 'ishi-製造-48', industry: '製造業', plan: 'paid', pitchCount: 5, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 30, departmentCount: 5, registeredMonth: '2024-07' },
  { id: '49', name: 'Acme卸売合同会社', slug: 'acme-卸売-49', industry: '卸売・小売', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 5, registeredMonth: '2024-07' },
  { id: '50', name: 'Nami卸売有限会社', slug: 'nami-卸売-50', industry: '卸売・小売', plan: 'free', pitchCount: 47, savedCount: 13, dismissedCount: 12, daysSinceLastPitch: 45, departmentCount: 5, registeredMonth: '2024-02' },
  { id: '51', name: 'Asahi卸売法人', slug: 'asahi-卸売-51', industry: '卸売・小売', plan: 'free', pitchCount: 2, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 45, departmentCount: 6, registeredMonth: '2024-06' },
  { id: '52', name: 'Kumo卸売株式会社', slug: 'kumo-卸売-52', industry: '卸売・小売', plan: 'free', pitchCount: 3, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 9, departmentCount: 3, registeredMonth: '2024-10' },
  { id: '53', name: 'Nami卸売合同会社', slug: 'nami-卸売-53', industry: '卸売・小売', plan: 'free', pitchCount: 1, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 120, departmentCount: 4, registeredMonth: '2024-11' },
  { id: '54', name: 'Sakura卸売有限会社', slug: 'sakura-卸売-54', industry: '卸売・小売', plan: 'free', pitchCount: 11, savedCount: 2, dismissedCount: 5, daysSinceLastPitch: 9, departmentCount: 3, registeredMonth: '2024-11' },
  { id: '55', name: 'Hoshi卸売法人', slug: 'hoshi-卸売-55', industry: '卸売・小売', plan: 'free', pitchCount: 11, savedCount: 1, dismissedCount: 5, daysSinceLastPitch: 14, departmentCount: 2, registeredMonth: '2024-11' },
  { id: '56', name: 'Tsuki卸売株式会社', slug: 'tsuki-卸売-56', industry: '卸売・小売', plan: 'paid', pitchCount: 22, savedCount: 3, dismissedCount: 7, daysSinceLastPitch: 5, departmentCount: 6, registeredMonth: '2024-08' },
  { id: '57', name: 'Hikari卸売合同会社', slug: 'hikari-卸売-57', industry: '卸売・小売', plan: 'free', pitchCount: 12, savedCount: 2, dismissedCount: 3, daysSinceLastPitch: 2, departmentCount: 4, registeredMonth: '2025-01' },
  { id: '58', name: 'Tsubasa卸売有限会社', slug: 'tsubasa-卸売-58', industry: '卸売・小売', plan: 'free', pitchCount: 12, savedCount: 1, dismissedCount: 3, daysSinceLastPitch: 5, departmentCount: 4, registeredMonth: '2024-08' },
  { id: '59', name: 'Hana卸売法人', slug: 'hana-卸売-59', industry: '卸売・小売', plan: 'free', pitchCount: 48, savedCount: 15, dismissedCount: 18, daysSinceLastPitch: 90, departmentCount: 4, registeredMonth: '2024-07' },
  { id: '60', name: 'Tani卸売株式会社', slug: 'tani-卸売-60', industry: '卸売・小売', plan: 'free', pitchCount: 60, savedCount: 17, dismissedCount: 27, daysSinceLastPitch: 20, departmentCount: 4, registeredMonth: '2025-01' },
  { id: '61', name: 'Hana卸売合同会社', slug: 'hana-卸売-61', industry: '卸売・小売', plan: 'paid', pitchCount: 30, savedCount: 8, dismissedCount: 8, daysSinceLastPitch: 30, departmentCount: 1, registeredMonth: '2024-06' },
  { id: '62', name: 'Nami卸売有限会社', slug: 'nami-卸売-62', industry: '卸売・小売', plan: 'free', pitchCount: 4, savedCount: 0, dismissedCount: 1, daysSinceLastPitch: 45, departmentCount: 5, registeredMonth: '2024-07' },
  { id: '63', name: 'Acme卸売法人', slug: 'acme-卸売-63', industry: '卸売・小売', plan: 'free', pitchCount: 1, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 120, departmentCount: 5, registeredMonth: '2024-12' },
  { id: '64', name: 'Hana卸売株式会社', slug: 'hana-卸売-64', industry: '卸売・小売', plan: 'free', pitchCount: 1, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 45, departmentCount: 5, registeredMonth: '2024-09' },
  { id: '65', name: 'Asahi卸売合同会社', slug: 'asahi-卸売-65', industry: '卸売・小売', plan: 'paid', pitchCount: 44, savedCount: 9, dismissedCount: 9, daysSinceLastPitch: 30, departmentCount: 6, registeredMonth: '2024-11' },
  { id: '66', name: 'Kumo卸売有限会社', slug: 'kumo-卸売-66', industry: '卸売・小売', plan: 'free', pitchCount: 8, savedCount: 2, dismissedCount: 2, daysSinceLastPitch: 45, departmentCount: 6, registeredMonth: '2024-10' },
  { id: '67', name: 'Kaze建設法人', slug: 'kaze-建設-67', industry: '建設・不動産', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 4, registeredMonth: '2024-01' },
  { id: '68', name: 'Sakura建設株式会社', slug: 'sakura-建設-68', industry: '建設・不動産', plan: 'free', pitchCount: 8, savedCount: 2, dismissedCount: 2, daysSinceLastPitch: 45, departmentCount: 4, registeredMonth: '2024-05' },
  { id: '69', name: 'Sakura建設合同会社', slug: 'sakura-建設-69', industry: '建設・不動産', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 6, registeredMonth: '2024-11' },
  { id: '70', name: 'Tsubasa建設有限会社', slug: 'tsubasa-建設-70', industry: '建設・不動産', plan: 'paid', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 2, registeredMonth: '2024-10' },
  { id: '71', name: 'Yamato建設法人', slug: 'yamato-建設-71', industry: '建設・不動産', plan: 'free', pitchCount: 11, savedCount: 3, dismissedCount: 3, daysSinceLastPitch: 20, departmentCount: 2, registeredMonth: '2025-01' },
  { id: '72', name: 'Hoshi建設株式会社', slug: 'hoshi-建設-72', industry: '建設・不動産', plan: 'free', pitchCount: 60, savedCount: 8, dismissedCount: 17, daysSinceLastPitch: 120, departmentCount: 5, registeredMonth: '2024-01' },
  { id: '73', name: 'Hoshi建設合同会社', slug: 'hoshi-建設-73', industry: '建設・不動産', plan: 'paid', pitchCount: 37, savedCount: 10, dismissedCount: 8, daysSinceLastPitch: 14, departmentCount: 6, registeredMonth: '2024-02' },
  { id: '74', name: 'Tani建設有限会社', slug: 'tani-建設-74', industry: '建設・不動産', plan: 'free', pitchCount: 20, savedCount: 2, dismissedCount: 7, daysSinceLastPitch: 30, departmentCount: 6, registeredMonth: '2024-02' },
  { id: '75', name: 'Tsubasa建設法人', slug: 'tsubasa-建設-75', industry: '建設・不動産', plan: 'free', pitchCount: 7, savedCount: 0, dismissedCount: 3, daysSinceLastPitch: 60, departmentCount: 4, registeredMonth: '2024-12' },
  { id: '76', name: 'Mizu建設株式会社', slug: 'mizu-建設-76', industry: '建設・不動産', plan: 'free', pitchCount: 9, savedCount: 1, dismissedCount: 3, daysSinceLastPitch: 90, departmentCount: 4, registeredMonth: '2025-01' },
  { id: '77', name: 'Niji建設合同会社', slug: 'niji-建設-77', industry: '建設・不動産', plan: 'free', pitchCount: 12, savedCount: 2, dismissedCount: 3, daysSinceLastPitch: 5, departmentCount: 2, registeredMonth: '2024-05' },
  { id: '78', name: 'Sora建設有限会社', slug: 'sora-建設-78', industry: '建設・不動産', plan: 'free', pitchCount: 49, savedCount: 5, dismissedCount: 22, daysSinceLastPitch: 9, departmentCount: 3, registeredMonth: '2024-08' },
  { id: '79', name: 'Tani建設法人', slug: 'tani-建設-79', industry: '建設・不動産', plan: 'paid', pitchCount: 34, savedCount: 8, dismissedCount: 15, daysSinceLastPitch: 90, departmentCount: 2, registeredMonth: '2024-01' },
  { id: '80', name: 'Mizu建設株式会社', slug: 'mizu-建設-80', industry: '建設・不動産', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 6, registeredMonth: '2024-12' },
  { id: '81', name: 'Kumo建設合同会社', slug: 'kumo-建設-81', industry: '建設・不動産', plan: 'free', pitchCount: 41, savedCount: 6, dismissedCount: 16, daysSinceLastPitch: 20, departmentCount: 3, registeredMonth: '2024-11' },
  { id: '82', name: 'Niji建設有限会社', slug: 'niji-建設-82', industry: '建設・不動産', plan: 'free', pitchCount: 9, savedCount: 3, dismissedCount: 3, daysSinceLastPitch: 30, departmentCount: 3, registeredMonth: '2024-12' },
  { id: '83', name: 'Umino医療法人', slug: 'umino-医療-83', industry: '医療・福祉', plan: 'free', pitchCount: 4, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 90, departmentCount: 2, registeredMonth: '2025-01' },
  { id: '84', name: 'Hikari医療株式会社', slug: 'hikari-医療-84', industry: '医療・福祉', plan: 'free', pitchCount: 8, savedCount: 1, dismissedCount: 3, daysSinceLastPitch: 120, departmentCount: 2, registeredMonth: '2024-05' },
  { id: '85', name: 'Midori医療合同会社', slug: 'midori-医療-85', industry: '医療・福祉', plan: 'free', pitchCount: 6, savedCount: 0, dismissedCount: 2, daysSinceLastPitch: 20, departmentCount: 5, registeredMonth: '2024-01' },
  { id: '86', name: 'Hoshi医療有限会社', slug: 'hoshi-医療-86', industry: '医療・福祉', plan: 'free', pitchCount: 3, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 2, departmentCount: 4, registeredMonth: '2024-10' },
  { id: '87', name: 'Sakura医療法人', slug: 'sakura-医療-87', industry: '医療・福祉', plan: 'free', pitchCount: 6, savedCount: 0, dismissedCount: 2, daysSinceLastPitch: 60, departmentCount: 4, registeredMonth: '2024-02' },
  { id: '88', name: 'Sakura医療株式会社', slug: 'sakura-医療-88', industry: '医療・福祉', plan: 'free', pitchCount: 10, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 120, departmentCount: 2, registeredMonth: '2024-05' },
  { id: '89', name: 'Tani医療合同会社', slug: 'tani-医療-89', industry: '医療・福祉', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 4, registeredMonth: '2024-04' },
  { id: '90', name: 'Midori医療有限会社', slug: 'midori-医療-90', industry: '医療・福祉', plan: 'free', pitchCount: 8, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 120, departmentCount: 5, registeredMonth: '2024-10' },
  { id: '91', name: 'Umino医療法人', slug: 'umino-医療-91', industry: '医療・福祉', plan: 'free', pitchCount: 19, savedCount: 2, dismissedCount: 7, daysSinceLastPitch: 9, departmentCount: 5, registeredMonth: '2024-04' },
  { id: '92', name: 'Midori医療株式会社', slug: 'midori-医療-92', industry: '医療・福祉', plan: 'paid', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 2, registeredMonth: '2024-05' },
  { id: '93', name: 'Kumo医療合同会社', slug: 'kumo-医療-93', industry: '医療・福祉', plan: 'free', pitchCount: 5, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 20, departmentCount: 6, registeredMonth: '2025-01' },
  { id: '94', name: 'Tsubasa医療有限会社', slug: 'tsubasa-医療-94', industry: '医療・福祉', plan: 'paid', pitchCount: 25, savedCount: 5, dismissedCount: 9, daysSinceLastPitch: 20, departmentCount: 1, registeredMonth: '2025-02' },
  { id: '95', name: 'Niji医療法人', slug: 'niji-医療-95', industry: '医療・福祉', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 1, registeredMonth: '2024-05' },
  { id: '96', name: 'Sakura金融株式会社', slug: 'sakura-金融-96', industry: '金融・保険', plan: 'free', pitchCount: 5, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 60, departmentCount: 5, registeredMonth: '2024-08' },
  { id: '97', name: 'Mori金融合同会社', slug: 'mori-金融-97', industry: '金融・保険', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 6, registeredMonth: '2024-02' },
  { id: '98', name: 'Umino金融有限会社', slug: 'umino-金融-98', industry: '金融・保険', plan: 'paid', pitchCount: 49, savedCount: 14, dismissedCount: 21, daysSinceLastPitch: 120, departmentCount: 4, registeredMonth: '2024-01' },
  { id: '99', name: 'Mizu金融法人', slug: 'mizu-金融-99', industry: '金融・保険', plan: 'free', pitchCount: 8, savedCount: 1, dismissedCount: 3, daysSinceLastPitch: 60, departmentCount: 3, registeredMonth: '2024-02' },
  { id: '100', name: 'Asahi金融株式会社', slug: 'asahi-金融-100', industry: '金融・保険', plan: 'free', pitchCount: 6, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 60, departmentCount: 5, registeredMonth: '2024-05' },
  { id: '101', name: 'Asahi金融合同会社', slug: 'asahi-金融-101', industry: '金融・保険', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 5, registeredMonth: '2025-01' },
  { id: '102', name: 'Yamato金融有限会社', slug: 'yamato-金融-102', industry: '金融・保険', plan: 'free', pitchCount: 13, savedCount: 3, dismissedCount: 4, daysSinceLastPitch: 14, departmentCount: 5, registeredMonth: '2024-09' },
  { id: '103', name: 'Niji金融法人', slug: 'niji-金融-103', industry: '金融・保険', plan: 'paid', pitchCount: 53, savedCount: 5, dismissedCount: 14, daysSinceLastPitch: 9, departmentCount: 6, registeredMonth: '2024-05' },
  { id: '104', name: 'Hana金融株式会社', slug: 'hana-金融-104', industry: '金融・保険', plan: 'free', pitchCount: 1, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 9, departmentCount: 1, registeredMonth: '2024-05' },
  { id: '105', name: 'Tsubasa金融合同会社', slug: 'tsubasa-金融-105', industry: '金融・保険', plan: 'free', pitchCount: 2, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 5, departmentCount: 4, registeredMonth: '2024-11' },
  { id: '106', name: 'Niji金融有限会社', slug: 'niji-金融-106', industry: '金融・保険', plan: 'paid', pitchCount: 31, savedCount: 5, dismissedCount: 13, daysSinceLastPitch: 60, departmentCount: 5, registeredMonth: '2024-04' },
  { id: '107', name: 'Tsuki飲食法人', slug: 'tsuki-飲食-107', industry: '飲食・宿泊', plan: 'free', pitchCount: 4, savedCount: 0, dismissedCount: 1, daysSinceLastPitch: 5, departmentCount: 3, registeredMonth: '2024-05' },
  { id: '108', name: 'Mizu飲食株式会社', slug: 'mizu-飲食-108', industry: '飲食・宿泊', plan: 'paid', pitchCount: 45, savedCount: 4, dismissedCount: 18, daysSinceLastPitch: 120, departmentCount: 2, registeredMonth: '2024-10' },
  { id: '109', name: 'Sora飲食合同会社', slug: 'sora-飲食-109', industry: '飲食・宿泊', plan: 'free', pitchCount: 8, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 60, departmentCount: 6, registeredMonth: '2024-06' },
  { id: '110', name: 'Asahi飲食有限会社', slug: 'asahi-飲食-110', industry: '飲食・宿泊', plan: 'free', pitchCount: 7, savedCount: 2, dismissedCount: 1, daysSinceLastPitch: 60, departmentCount: 4, registeredMonth: '2024-12' },
  { id: '111', name: 'Hikari飲食法人', slug: 'hikari-飲食-111', industry: '飲食・宿泊', plan: 'free', pitchCount: 54, savedCount: 5, dismissedCount: 18, daysSinceLastPitch: 120, departmentCount: 4, registeredMonth: '2024-06' },
  { id: '112', name: 'Tsubasa飲食株式会社', slug: 'tsubasa-飲食-112', industry: '飲食・宿泊', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 1, registeredMonth: '2025-02' },
  { id: '113', name: 'Hana飲食合同会社', slug: 'hana-飲食-113', industry: '飲食・宿泊', plan: 'free', pitchCount: 5, savedCount: 1, dismissedCount: 1, daysSinceLastPitch: 30, departmentCount: 4, registeredMonth: '2025-02' },
  { id: '114', name: 'Hoshi飲食有限会社', slug: 'hoshi-飲食-114', industry: '飲食・宿泊', plan: 'free', pitchCount: 53, savedCount: 16, dismissedCount: 11, daysSinceLastPitch: 5, departmentCount: 2, registeredMonth: '2024-04' },
  { id: '115', name: 'Hoshi飲食法人', slug: 'hoshi-飲食-115', industry: '飲食・宿泊', plan: 'free', pitchCount: 40, savedCount: 11, dismissedCount: 9, daysSinceLastPitch: 9, departmentCount: 1, registeredMonth: '2024-12' },
  { id: '116', name: 'Mori飲食株式会社', slug: 'mori-飲食-116', industry: '飲食・宿泊', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 5, registeredMonth: '2024-03' },
  { id: '117', name: 'Mori教育合同会社', slug: 'mori-教育-117', industry: '教育', plan: 'free', pitchCount: 11, savedCount: 1, dismissedCount: 2, daysSinceLastPitch: 45, departmentCount: 4, registeredMonth: '2024-10' },
  { id: '118', name: 'Niji教育有限会社', slug: 'niji-教育-118', industry: '教育', plan: 'paid', pitchCount: 22, savedCount: 5, dismissedCount: 7, daysSinceLastPitch: 2, departmentCount: 3, registeredMonth: '2025-01' },
  { id: '119', name: 'Tsuki教育法人', slug: 'tsuki-教育-119', industry: '教育', plan: 'paid', pitchCount: 23, savedCount: 7, dismissedCount: 11, daysSinceLastPitch: 20, departmentCount: 6, registeredMonth: '2024-11' },
  { id: '120', name: 'Kumo教育株式会社', slug: 'kumo-教育-120', industry: '教育', plan: 'free', pitchCount: 5, savedCount: 0, dismissedCount: 1, daysSinceLastPitch: 14, departmentCount: 3, registeredMonth: '2024-07' },
  { id: '121', name: 'Kumo教育合同会社', slug: 'kumo-教育-121', industry: '教育', plan: 'free', pitchCount: 12, savedCount: 4, dismissedCount: 4, daysSinceLastPitch: 20, departmentCount: 6, registeredMonth: '2024-01' },
  { id: '122', name: 'Yamato教育有限会社', slug: 'yamato-教育-122', industry: '教育', plan: 'free', pitchCount: 16, savedCount: 4, dismissedCount: 7, daysSinceLastPitch: 14, departmentCount: 2, registeredMonth: '2024-10' },
  { id: '123', name: 'Hikari教育法人', slug: 'hikari-教育-123', industry: '教育', plan: 'paid', pitchCount: 52, savedCount: 15, dismissedCount: 22, daysSinceLastPitch: 9, departmentCount: 6, registeredMonth: '2024-11' },
  { id: '124', name: 'Tsuki教育株式会社', slug: 'tsuki-教育-124', industry: '教育', plan: 'paid', pitchCount: 32, savedCount: 6, dismissedCount: 7, daysSinceLastPitch: 20, departmentCount: 2, registeredMonth: '2024-06' },
  { id: '125', name: 'Umino運輸合同会社', slug: 'umino-運輸-125', industry: '運輸・物流', plan: 'free', pitchCount: 9, savedCount: 1, dismissedCount: 3, daysSinceLastPitch: 20, departmentCount: 3, registeredMonth: '2025-02' },
  { id: '126', name: 'Tsubasa運輸有限会社', slug: 'tsubasa-運輸-126', industry: '運輸・物流', plan: 'free', pitchCount: 43, savedCount: 13, dismissedCount: 18, daysSinceLastPitch: 60, departmentCount: 2, registeredMonth: '2024-02' },
  { id: '127', name: 'Asahi運輸法人', slug: 'asahi-運輸-127', industry: '運輸・物流', plan: 'free', pitchCount: 59, savedCount: 18, dismissedCount: 21, daysSinceLastPitch: 5, departmentCount: 1, registeredMonth: '2025-01' },
  { id: '128', name: 'Yamato運輸株式会社', slug: 'yamato-運輸-128', industry: '運輸・物流', plan: 'free', pitchCount: 2, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 120, departmentCount: 1, registeredMonth: '2024-07' },
  { id: '129', name: 'Sakura運輸合同会社', slug: 'sakura-運輸-129', industry: '運輸・物流', plan: 'paid', pitchCount: 43, savedCount: 13, dismissedCount: 15, daysSinceLastPitch: 120, departmentCount: 6, registeredMonth: '2024-04' },
  { id: '130', name: 'Mizu運輸有限会社', slug: 'mizu-運輸-130', industry: '運輸・物流', plan: 'paid', pitchCount: 57, savedCount: 11, dismissedCount: 13, daysSinceLastPitch: 2, departmentCount: 1, registeredMonth: '2024-05' },
  { id: '131', name: 'Hana運輸法人', slug: 'hana-運輸-131', industry: '運輸・物流', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 4, registeredMonth: '2024-11' },
  { id: '132', name: 'Tsuki運輸株式会社', slug: 'tsuki-運輸-132', industry: '運輸・物流', plan: 'free', pitchCount: 12, savedCount: 2, dismissedCount: 2, daysSinceLastPitch: 60, departmentCount: 3, registeredMonth: '2024-10' },
  { id: '133', name: 'Yamato運輸合同会社', slug: 'yamato-運輸-133', industry: '運輸・物流', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 1, registeredMonth: '2025-02' },
  { id: '134', name: 'Sora人材有限会社', slug: 'sora-人材-134', industry: '人材・コンサル', plan: 'paid', pitchCount: 36, savedCount: 12, dismissedCount: 11, daysSinceLastPitch: 45, departmentCount: 1, registeredMonth: '2024-05' },
  { id: '135', name: 'Nami人材法人', slug: 'nami-人材-135', industry: '人材・コンサル', plan: 'paid', pitchCount: 42, savedCount: 6, dismissedCount: 16, daysSinceLastPitch: 2, departmentCount: 2, registeredMonth: '2024-01' },
  { id: '136', name: 'Mori人材株式会社', slug: 'mori-人材-136', industry: '人材・コンサル', plan: 'paid', pitchCount: 49, savedCount: 15, dismissedCount: 17, daysSinceLastPitch: 120, departmentCount: 3, registeredMonth: '2024-04' },
  { id: '137', name: 'Kaze人材合同会社', slug: 'kaze-人材-137', industry: '人材・コンサル', plan: 'paid', pitchCount: 51, savedCount: 16, dismissedCount: 12, daysSinceLastPitch: 9, departmentCount: 2, registeredMonth: '2024-09' },
  { id: '138', name: 'Mori人材有限会社', slug: 'mori-人材-138', industry: '人材・コンサル', plan: 'free', pitchCount: 0, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 999, departmentCount: 5, registeredMonth: '2025-01' },
  { id: '139', name: 'Sakura人材法人', slug: 'sakura-人材-139', industry: '人材・コンサル', plan: 'free', pitchCount: 3, savedCount: 0, dismissedCount: 0, daysSinceLastPitch: 5, departmentCount: 4, registeredMonth: '2024-12' },
  { id: '140', name: 'Tani人材株式会社', slug: 'tani-人材-140', industry: '人材・コンサル', plan: 'free', pitchCount: 6, savedCount: 0, dismissedCount: 2, daysSinceLastPitch: 120, departmentCount: 3, registeredMonth: '2024-01' },
];

// 月次の新規登録数と累計（成長グラフ用）
export interface MonthlySignup { month: string; newCount: number; cumulative: number; }
export const mockMonthlySignups: MonthlySignup[] = [
  { month: '2024-01', newCount: 12, cumulative: 12 },
  { month: '2024-02', newCount: 9, cumulative: 21 },
  { month: '2024-03', newCount: 3, cumulative: 24 },
  { month: '2024-04', newCount: 10, cumulative: 34 },
  { month: '2024-05', newCount: 15, cumulative: 49 },
  { month: '2024-06', newCount: 10, cumulative: 59 },
  { month: '2024-07', newCount: 10, cumulative: 69 },
  { month: '2024-08', newCount: 10, cumulative: 79 },
  { month: '2024-09', newCount: 7, cumulative: 86 },
  { month: '2024-10', newCount: 12, cumulative: 98 },
  { month: '2024-11', newCount: 13, cumulative: 111 },
  { month: '2024-12', newCount: 8, cumulative: 119 },
  { month: '2025-01', newCount: 13, cumulative: 132 },
  { month: '2025-02', newCount: 8, cumulative: 140 },
  { month: '2025-03', newCount: 0, cumulative: 140 },
  { month: '2025-04', newCount: 0, cumulative: 140 },
  { month: '2025-05', newCount: 0, cumulative: 140 },
];

// 却下理由の分布（マッチング品質の指標。売り手の改善材料）
export interface DismissReasonStat { reason: string; count: number; }
export const mockDismissReasons: DismissReasonStat[] = [
  { reason: '条件に合わない', count: 283 },
  { reason: '時期尚早', count: 123 },
  { reason: '予算が合わない', count: 194 },
  { reason: '既存サービスで充足', count: 177 },
  { reason: '情報不足', count: 106 },
];
